// database schema definitions - typescript interfaces for all database tables
// defines structure for profiles, entries, entities, habits, habitLogs, dailyAggregates, settings
//
// WHAT WE'RE CREATING:
// - TypeScript interfaces that define the shape of all data in our database
// - Each interface represents one table (Profile, Entry, Entity, Habit, HabitLog, DailyAggregate, Settings)
// - These interfaces are used by TypeScript to catch errors and provide autocomplete
// - They're also used by Dexie to set up the database structure
//
// OWNERSHIP:
// - Aadil creates this file with all interfaces
// - Michael adds Entity interface details (on separate branch)
// - Zayn requests any additional fields early (coordinate with Aadil)
//
// COORDINATION NOTES:
// - Aadil creates file first with all basic interfaces
// - Michael and Zayn review before adding their specific fields
// - Use Git branches when adding new fields
//
// CONTEXT FOR AI ASSISTANTS:
// - This file defines the data structure for our local-first IndexedDB database
// - All data is stored locally in the browser (privacy-first approach)
// - Each interface represents a table in our database
// - Optional `id?` fields are auto-generated by Dexie (our IndexedDB wrapper)
// - Dates are stored as strings in "yyyy-mm-dd" format for easy querying and sorting
// - Rich text content is stored as HTML strings (from our rich text editor)
//
// DEVELOPMENT NOTES:
// - When adding new fields, update the Dexie schema in dexie.ts
// - Consider backward compatibility - existing users may have old data structures
// - All text fields should be strings, numbers for numeric data, booleans for flags
// - Use optional fields (?) for data that may not exist initially
//
// TODO: define all interfaces below
// - Profile: user profile data (name, created date, etc.)
// - Entry: journal entries with rich text, mood, weather, date
// - Entity: extracted entities from entries (people, topics) for prompt generation
// - Habit: habit definitions (name, type, target, color, etc.)
// - HabitLog: daily habit completion records (for streaks and progress)
// - DailyAggregate: pre-computed daily stats (word counts, top topics, etc.)
// - Settings: app settings (PIN hash, AI preferences, appearance, blacklist)
//
// SYNTAX: export interface TableName { id?: number; field: type; ... }

// TODO: implement all schema interfaces

